specup/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.user_password, name='user_password'),
    path('profile/<name>/', views.profile, name='profile'),
    path('profile/<int:pk>/follow/', views.follow, name='follow'),
]

specup/argorithms/urls.py
from django.urls import path
from . import views

app_name = "argorithms"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete', views.comments_delete, name='comments_delete'),
    path('<int:pk>/like/', views.like, name='like'),
]

specup/specup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('argorithms/', include('argorithms.urls')),
    path('accounts/', include('accounts.urls')),
]

specup/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang='ko'>
<head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
   <title>Developer SPEC UP!</title>
   {% bootstrap_css %}
</head>
<body>
<div class='container'>
<br>
<div class="row">
  <a href="{% url 'argorithms:create' %}">[새로운 알고리즘 사이트 등록]</a>
  <a href="{% url 'argorithms:index' %}">[알고리즘 사이트 목록]</a>
  {% if user.is_authenticated %}
  <a href="{% url 'accounts:update' %}">[프로필 수정]</a>
  <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <a href='#' onclick='this.parentNode.submit(); return false;'>[로그아웃]</a>
  </form>
  <a href="{% url 'accounts:profile' user %}">[프로필]</a>
  {% else %}
    <a href="{% url 'accounts:signup' %}">[회원가입]</a>
    <a href="{% url 'accounts:login' %}">[로그인]</a>
  {% endif %}
  {% comment %} <form action="{% url 'accounts:delete' %}" method="post">
    {% csrf_token %}
    <a href='#' onclick='this.parentNode.submit(); return false;'>[회원삭제]</a>
  </form> {% endcomment %}

  <a href="{% url 'accounts:index' %}">[회원목록]</a>
</div>
<br>
<div class="row">
  {% if user.is_authenticated %}
    <h5>{{user}}님 반갑습니다.</h5>
  {% else %}
    <h5>로그인 부탁드려요~~!</h5>
  {% endif %}
</div>
<br>
<br>
<h1>Developer SPEC UP!</h1>
<hr>
{% block content %}
{% endblock content %}
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>