specup/argorithms/urls.py
from django.urls import path
from . import views

app_name = "argorithms"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete', views.comments_delete, name='comments_delete'),
    path('<int:pk>/like/', views.like, name='like'),
]

specup/specup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('argorithms/', include('argorithms.urls')),
    path('accounts/', include('accounts.urls')),
]

specup/argorithms/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Argorithm(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_argorithms')
    title = models.CharField(max_length=30)
    content = models.TextField()
    url = models.CharField(max_length=200, default='')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    argorithm = models.ForeignKey(Argorithm, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.content

specup/argorithms/forms.py
from django import forms
from .models import Argorithm, Comment


class ArgorithmForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        )
    )

    content = forms.CharField(
        widget=forms.Textarea(
            attrs = {
                'class':'form-control',
            }
        )
    )

    url = forms.CharField(
        widget=forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        )
    )

    class Meta:
        model = Argorithm
        fields = ['title', 'content', 'url']


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        )
    )

    class Meta:
        model = Comment
        fields = ['content']

specup/argorithms/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_safe, require_http_methods
from .models import Argorithm, Comment
from .forms import ArgorithmForm, CommentForm

# Create your views here.
@require_safe
def index(request):
    argorithms = Argorithm.objects.all()
    context = {
        'argorithms':argorithms,
    }
    return render(request, "argorithms/index.html", context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == "POST":
        form = ArgorithmForm(request.POST)
        if form.is_valid():
            argorithm = form.save(commit=False)
            argorithm.user = request.user
            argorithm.save()
            return redirect("argorithms:index")
    else:
        form = ArgorithmForm()
    context = {
        "form":form,
    }
    return render(request, "argorithms/create.html", context)
    

@require_safe
def detail(request, pk):
    argorithm = get_object_or_404(Argorithm, pk=pk)
    comment_form = CommentForm()
    comments = argorithm.comment_set.all()
    context = {
        'argorithm':argorithm,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request, 'argorithms/detail.html', context)

@require_http_methods(['GET','POST'])
def update(request, pk):
    argorithm = get_object_or_404(Argorithm, pk=pk)
    if request.user == argorithm.user:
        if request.method == "POST":
            form = ArgorithmForm(request.POST, instance=argorithm)
            if form.is_valid():
                form.save()
                return redirect("argorithms:detail", pk)
        else:
            form = ArgorithmForm(instance=argorithm)
    else:
        return redirect("argorithms:index")
    context = {
        'form':form,
        'argorithm':argorithm,
    }
    return render(request, "argorithms/update.html", context)

@require_POST
def delete(request, pk):
    argorithm = get_object_or_404(Argorithm, pk=pk)
    if request.user == argorithm.user:
        argorithm.delete()
    return redirect("argorithms:index")

@require_POST
def comments_create(request, pk):
    argorithm = get_object_or_404(Argorithm, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.argorithm = argorithm
        comment.save()
        return redirect("argorithms:detail", pk)
    context = {
        "comment_form" : comment_form,
    }
    return render(request, 'argorithms/detail.html', context)

@require_POST
def comments_delete(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('argorithms:detail', pk)

@require_POST
def like(request, pk):
    # 인증된 사용자만 가능
    if request.user.is_authenticated:
        argorithm = get_object_or_404(Argorithm, pk=pk)
        if argorithm.like_users.filter(pk=request.user.pk).exists():
            # 좋아요 취소
            argorithm.like_users.remove(request.user)
        else:
            # 좋아요
            argorithm.like_users.add(request.user)
        return redirect('argorithms:detail', pk)
    return redirect('accounts:login')

specup/argorithms/templates/argorithms/create.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'argorithms:create' %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="등록">
</form>
{% endblock content %}

specup/argorithms/templates/argorithms/detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-5">
      <h2>{{argorithm.title}}</h2>
    </div>
    <div class="col-4">
      <h3>작성자 : {{argorithm.user}}</h3>
    </div>
    <div class="col-1">
      <form action="{% url 'argorithms:like' argorithm.pk %}" method="post">
      {% csrf_token %}
      {% if user in argorithm.like_users.all %}
        <button type="submit" class="btn btn-sm">좋아요 취소</button>
      {% else %}
        <button type="submit" class="btn btn-primary btn-sm">좋아요</button>
      {% endif %}
      </form>
    </div>
    <div class="col-2">
      ♥ {{argorithm.like_users.count}}
    </div>
  </div>
  <hr>
  <h6>{{argorithm.content}}</h6>
  <br>
  <p>[주소] <a href="{{argorithm.url}}"> {{argorithm.url}} </a></p>
  <br>
  <a href="{% url 'argorithms:update' argorithm.pk %}">[글 수정]</a>
  <form action="{% url 'argorithms:delete' argorithm.pk %}" method="post">
    {% csrf_token %}
    <a href='#' onclick='this.parentNode.submit(); return false;'>[글 삭제]</a>
  </form>
  <br>
  <br>
  <a href="{% url 'argorithms:index' %}">[BACK]</a>
  <hr>
  {% for comment in comments %}
  <p>
    [{{comment.user}}]: {{comment}}
    <form action="{% url 'argorithms:comments_delete' argorithm.pk comment.pk %}" method="post">
    {% csrf_token %}
    <a href='#' onclick='this.parentNode.submit(); return false;'>[댓글 삭제]</a>
    </form>
  </p>
  {% endfor %}
  <br>
  <form action="{% url 'argorithms:comments_create' argorithm.pk %}" method="post">
    {% csrf_token %}
    {{comment_form}}
    <a href='#' onclick='this.parentNode.submit(); return false;'>[댓글 작성]</a>
  </form>
{% endblock content %}

specup/argorithms/templates/argorithms/index.html
{% extends 'base.html' %}
{% block content %}
<h2>알고리즘 사이트</h2>
<hr>
{% for argorithm in argorithms %}
  <h4><a href="{% url 'argorithms:detail' argorithm.pk %}">{{argorithm.title}}</a></h4>
  <br>
{% endfor %}
{% endblock content %}

specup/argorithms/templates/argorithms/update.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'argorithms:update' argorithm.pk %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="수정">
</form>
{% endblock content %}