specup/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.user_password, name='user_password'),
    path('profile/<name>/', views.profile, name='profile'),
    path('profile/<int:pk>/follow/', views.follow, name='follow'),
]

specup/specup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('argorithms/', include('argorithms.urls')),
    path('accounts/', include('accounts.urls')),
]

specup/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

specup/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ("email", "first_name", "last_name")

specup/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
@require_safe
def index(request):
    users = get_user_model().objects.all()
    context={
        "users":users,
    }
    return render(request, "accounts/index.html", context)

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect("argorithms:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user_user = form.save()
            auth_login(request, user_user)
            return redirect('argorithms:index')
    else:
        form = CustomUserCreationForm()
    context = {
        "form":form,
    }
    return render(request, "accounts/signup.html", context)

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect("argorithms:index")

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'argorithms:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, "accounts/login.html", context)

@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('argorithms:index')

@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('argorithms:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context={
        'form':form,
    }
    return render(request, 'accounts/update.html', context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('argorithms:index')

@login_required
@require_http_methods(['GET', 'POST'])
def user_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = PasswordChangeForm(request.user)
    context={
        "form":form,
    }
    return render(request, "accounts/user_password.html", context)

@login_required
def profile(request, name):
    User = get_user_model()
    user_data = get_object_or_404(User, username=name)
    context={
        "user_data":user_data,
    }
    return render(request, "accounts/profile.html", context)

@require_POST
def follow(request, pk):
    # 인증된 사용자만 가능
    if request.user.is_authenticated:
        you = get_object_or_404(get_user_model(), pk=pk)
        me = request.user
        if me != you:
            if you.followers.filter(pk=me.pk).exists():
                you.followers.remove(me)
            else:
                you.followers.add(me)
    return redirect('accounts:profile', you.username)

specup/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
{% for u in users %}
  <h6>{{u}}</h6>
{% endfor %}
{% endblock content %}

specup/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-primary">로그인</button>
</form>
{% endblock content %}

specup/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<h6>{{user_data.username}}</h6>
<h6>{{user_data.email}}</h6>
<h6>{{user_data.last_name}} {{user_data.first_name}}</h6>
<h6>팔로우 수 : {{user_data.followers.count}}</h6>
<form action="{% url 'accounts:follow' user_data.pk %}" method="post">
  {% csrf_token %}
  {% if user in user_data.followers.all %}
    <button type="submit" class="btn btn-primary">팔로우 취소</button>
  {% else %}
    <button type="submit" class="btn btn-primary">팔로우</button>
  {% endif %}
</form>
{% endblock content %}

specup/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-primary">회원가입</button>
</form>
{% endblock content %}

specup/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:update' %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button class = "btn btn-primary">프로필 수정</button>
</form>
{% endblock content %}

specup/accounts/templates/accounts/user_password.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:user_password' %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-primary">비밀번호 수정</button>
</form>
{% endblock content %}